--[[
--Created Date: Friday April 4th 2025 11:22:33 pm CEST
--Author: Cosmovyz
-------
--Last Modified: Tuesday October 21st 2025 10:29:35 am CEST
--Modified By: Cosmovyz
--]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Guard = require(ReplicatedStorage.Packages.Guard)
local Red = require(ReplicatedStorage.Packages.Red)

return Red.Event("ClientLoaded", function()
	return
end)
